name: Gradle Error Checker

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Check for errors.
        uses: github/super-linter@v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: false